=== dmitriykozlov/cp2020-tool/src/assets/weapons.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Cyberpunk2020Weapon",
  "description": "A schema representing a weapon from Cyberpunk 2020.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Weapon's full name."
      },
      "group": {
        "type": "string",
        "enum": [
          "Light autopistols",
          "Medium autopistols",
          "Heavy autopistols",
          "Very heavy autopistols",
          "Light SMG",
          "Medium SMG",
          "Heavy SMG",
          "Assault rifles",
          "Shotguns",
          "Heavy weapons"
        ],
        "description": "Category or group of the weapon (e.g., Light Autopistols, Heavy SMG, etc.)."
      },
      "type": {
        "type": "string",
        "enum": [
          "P",
          "SMG",
          "RIF",
          "SHT",
          "HVY"
        ],
        "description": "Weapon type code (e.g., P = Pistol, SMG, RIF = Rifle, etc.)."
      },
      "wa": {
        "type": "integer",
        "description": "Weapon Accuracy modifier."
      },
      "con": {
        "type": "string",
        "enum": [
          "P",
          "J",
          "L",
          "N"
        ],
        "description": "Concealability rating (P = Pocket, J = Jacket, L = Long Coat, N = Not concealable)."
      },
      "avail": {
        "type": "string",
        "enum": [
          "E",
          "C",
          "P",
          "R"
        ],
        "description": "Availability rating (E = Excellent, C = Common, R = Rare, P = Poor)."
      },
      "dmg": {
        "type": "string",
        "description": "Damage dice rolled for the weapon."
      },
      "ammo": {
        "type": "string",
        "description": "Ammunition type or caliber."
      },
      "shots": {
        "type": [
          "integer",
          "string"
        ],
        "description": "Number of shots available. Might be 'NA' for melee weapons."
      },
      "rof": {
        "type": "integer",
        "description": "Rate of fire (number of shots per round)."
      },
      "rel": {
        "type": "string",
        "enum": [
          "VR",
          "ST",
          "UR"
        ],
        "description": "Reliability rating (VR = Very Reliable, ST = Standard, UR = Unreliable)."
      },
      "range": {
        "type": "integer",
        "description": "Effective weapon range (meters)."
      },
      "cost": {
        "type": "number",
        "description": "Weapon cost in eurobucks."
      }
    }
  },
  "required": [
    "name",
    "group",
    "type",
    "wa",
    "con",
    "avail",
    "Damage",
    "ammo",
    "shots",
    "rof",
    "rel",
    "range",
    "cost"
  ]
}

=== dmitriykozlov/cp2020-tool/src/assets/weapons.json
[
  {
    "name": "BudgetArms C-13",
    "group": "Light autopistols",
    "type": "P",
    "wa": -1,
    "con": "P",
    "avail": "E",
    "dmg": "1D6",
    "ammo": "5mm",
    "shots": 8,
    "rof": 2,
    "rel": "ST",
    "range": 50,
    "cost": 75
  },
  {
    "name": "Dai Lung Cybermag 15",
    "group": "Light autopistols",
    "type": "P",
    "wa": -1,
    "con": "P",
    "avail": "C",
    "dmg": "1D6+1",
    "ammo": "6mm",
    "shots": 10,
    "rof": 2,
    "rel": "UR",
    "range": 50,
    "cost": 50
  },
  {
    "name": "Federated Arms X-22",
    "group": "Light autopistols",
    "type": "P",
    "wa": 0,
    "con": "P",
    "avail": "E",
    "dmg": "1D6+1",
    "ammo": "6mm",
    "shots": 10,
    "rof": 2,
    "rel": "ST",
    "range": 50,
    "cost": 150
  },
  {
    "name": "Mlitech Arms Avenger",
    "group": "Medium autopistols",
    "type": "P",
    "wa": 0,
    "con": "J",
    "avail": "E",
    "dmg": "2D6+1",
    "ammo": "9mm",
    "shots": 10,
    "rof": 2,
    "rel": "VR",
    "range": 50,
    "cost": 250
  },
  {
    "name": "Dai Lung Streetmaster",
    "group": "Medium autopistols",
    "type": "P",
    "wa": 0,
    "con": "J",
    "avail": "E",
    "dmg": "2D6+3",
    "ammo": "10mm",
    "shots": 12,
    "rof": 2,
    "rel": "UR",
    "range": 50,
    "cost": 250
  },
  {
    "name": "Federated Arms X-9mm",
    "group": "Medium autopistols",
    "type": "P",
    "wa": 0,
    "con": "J",
    "avail": "E",
    "dmg": "2D6+1",
    "ammo": "9mm",
    "shots": 12,
    "rof": 2,
    "rel": "ST",
    "range": 50,
    "cost": 300
  },
  {
    "name": "BudgetArms Auto",
    "group": "Heavy autopistols",
    "type": "P",
    "wa": -1,
    "con": "J",
    "avail": "E",
    "dmg": "3D6",
    "ammo": "11mm",
    "shots": 8,
    "rof": 2,
    "rel": "UR",
    "range": 50,
    "cost": 350
  },
  {
    "name": "Sternmeyer Type 35",
    "group": "Heavy autopistols",
    "type": "P",
    "wa": 0,
    "con": "J",
    "avail": "C",
    "dmg": "3D6",
    "ammo": "11mm",
    "shots": 8,
    "rof": 2,
    "rel": "VR",
    "range": 50,
    "cost": 400
  },
  {
    "name": "Armalite 44",
    "group": "Very heavy autopistols",
    "type": "P",
    "wa": 0,
    "con": "J",
    "avail": "E",
    "dmg": "4D6+1",
    "ammo": "12mm",
    "shots": 8,
    "rof": 1,
    "rel": "ST",
    "range": 50,
    "cost": 450
  },
  {
    "name": "Colt AMT Model 2000",
    "group": "Very heavy autopistols",
    "type": "P",
    "wa": 0,
    "con": "J",
    "avail": "C",
    "dmg": "4D6+1",
    "ammo": "12mm",
    "shots": 8,
    "rof": 1,
    "rel": "VR",
    "range": 50,
    "cost": 500
  },
  {
    "name": "Uzi Miniauto 9",
    "group": "Light SMG",
    "type": "SMG",
    "wa": 1,
    "con": "J",
    "avail": "E",
    "dmg": "2D6+1",
    "ammo": "9mm",
    "shots": 30,
    "rof": 35,
    "rel": "VR",
    "range": 150,
    "cost": 475
  },
  {
    "name": "H&K MP-2013",
    "group": "Light SMG",
    "type": "SMG",
    "wa": 1,
    "con": "J",
    "avail": "C",
    "dmg": "2D6+3",
    "ammo": "10mm",
    "shots": 35,
    "rof": 32,
    "rel": "ST",
    "range": 150,
    "cost": 450
  },
  {
    "name": "Fed. Arms Tech Assault II",
    "group": "Light SMG",
    "type": "SMG",
    "wa": 1,
    "con": "J",
    "avail": "C",
    "dmg": "1D6+1",
    "ammo": "6mm",
    "shots": 50,
    "rof": 25,
    "rel": "ST",
    "range": 150,
    "cost": 400
  },
  {
    "name": "Arasaka Minami 10",
    "group": "Medium SMG",
    "type": "SMG",
    "wa": 0,
    "con": "J",
    "avail": "E",
    "dmg": "2D6+3",
    "ammo": "10mm",
    "shots": 40,
    "rof": 20,
    "rel": "VR",
    "range": 200,
    "cost": 500
  },
  {
    "name": "H&K MPK-9",
    "group": "Medium SMG",
    "type": "SMG",
    "wa": 1,
    "con": "J",
    "avail": "C",
    "dmg": "2D6+1",
    "ammo": "9mm",
    "shots": 35,
    "rof": 25,
    "rel": "ST",
    "range": 200,
    "cost": 520
  },
  {
    "name": "Sternmeyer SMG 21",
    "group": "Heavy SMG",
    "type": "SMG",
    "wa": -1,
    "con": "L",
    "avail": "E",
    "dmg": "3D6",
    "ammo": "11mm",
    "shots": 30,
    "rof": 15,
    "rel": "VR",
    "range": 200,
    "cost": 500
  },
  {
    "name": "H&K MPK-11",
    "group": "Heavy SMG",
    "type": "SMG",
    "wa": 0,
    "con": "L",
    "avail": "C",
    "dmg": "4D6+1",
    "ammo": "12mm",
    "shots": 30,
    "rof": 20,
    "rel": "ST",
    "range": 200,
    "cost": 700
  },
  {
    "name": "Ingram MAC 14",
    "group": "Heavy SMG",
    "type": "SMG",
    "wa": -2,
    "con": "L",
    "avail": "E",
    "dmg": "4D6+1",
    "ammo": "12mm",
    "shots": 20,
    "rof": 10,
    "rel": "ST",
    "range": 200,
    "cost": 650
  },
  {
    "name": "Militech Ronin Light Assault",
    "group": "Assault rifles",
    "type": "RIF",
    "wa": 1,
    "con": "N",
    "avail": "C",
    "dmg": "5D6",
    "ammo": "5.56",
    "shots": 35,
    "rof": 30,
    "rel": "VR",
    "range": 400,
    "cost": 450
  },
  {
    "name": "AKR-20 Medium Assault",
    "group": "Assault rifles",
    "type": "RIF",
    "wa": 0,
    "con": "N",
    "avail": "C",
    "dmg": "5D6",
    "ammo": "5.56",
    "shots": 30,
    "rof": 30,
    "rel": "ST",
    "range": 400,
    "cost": 500
  },
  {
    "name": "FN-RAL Heavy Assault Rifle",
    "group": "Assault rifles",
    "type": "RIF",
    "wa": -1,
    "con": "N",
    "avail": "C",
    "dmg": "6D6+2",
    "ammo": "7.62",
    "shots": 30,
    "rof": 30,
    "rel": "VR",
    "range": 400,
    "cost": 600
  },
  {
    "name": "Kalishnikov A-80 Hvy. Rifle",
    "group": "Assault rifles",
    "type": "RIF",
    "wa": -1,
    "con": "N",
    "avail": "E",
    "dmg": "6D6+3",
    "ammo": "7.62",
    "shots": 35,
    "rof": 25,
    "rel": "ST",
    "range": 400,
    "cost": 550
  },
  {
    "name": "Arasaka Rapid Assault 12",
    "group": "Shotguns",
    "type": "SHT",
    "wa": -1,
    "con": "N",
    "avail": "C",
    "dmg": "4D6",
    "ammo": "00",
    "shots": 20,
    "rof": 10,
    "rel": "ST",
    "range": 50,
    "cost": 900
  },
  {
    "name": "Sternmeyer Stakeout 10",
    "group": "Shotguns",
    "type": "SHT",
    "wa": -2,
    "con": "N",
    "avail": "R",
    "dmg": "4D6",
    "ammo": "00",
    "shots": 10,
    "rof": 2,
    "rel": "ST",
    "range": 50,
    "cost": 450
  },
  {
    "name": "Barrett-Arasaka Light 20mm",
    "group": "Heavy weapons",
    "type": "HVY",
    "wa": 0,
    "con": "N",
    "avail": "R",
    "dmg": "4D10",
    "ammo": "AP(20/9mm)",
    "shots": 10,
    "rof": 1,
    "rel": "VR",
    "range": 450,
    "cost": 2000
  },
  {
    "name": "Scorpion 16 Missile Launcher",
    "group": "Heavy weapons",
    "type": "HVY",
    "wa": -1,
    "con": "N",
    "avail": "R",
    "dmg": "7D10",
    "ammo": "Missile",
    "shots": 1,
    "rof": 1,
    "rel": "VR",
    "range": 1000,
    "cost": 3000
  },
  {
    "name": "Militech Arms RPG-A",
    "group": "Heavy weapons",
    "type": "HVY",
    "wa": -2,
    "con": "N",
    "avail": "R",
    "dmg": "6D10",
    "ammo": "Rocket",
    "shots": 1,
    "rof": 1,
    "rel": "VR",
    "range": 750,
    "cost": 1500
  }
]
